replicaCount: 1

image:
  repository: "${REGISTRY}/${REPOSITORY}"
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart version.
  tag: "${IMAGE_TAG}"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: ""
  annotations: {}

service:
  selector:
    app.kubernetes.io/name: forntend
  type: ClusterIP
  name: frontend
  protocol: TCP
  port: 80
  targetPort: 4200

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: alb
  hosts:
  - host: meu-app.com.br
    paths:
      - path: /frontend
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
  tls: []

resources:
   limits:
     cpu: 150m
     memory: 512Mi
   requests:
     cpu: 100m
     memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

