replicaCount: 1

image:
  repository: "${REGISTRY}/${REPOSITORY}"
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart version.
  tag: "${IMAGE_TAG}"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""


podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
     kubernetes.io/ingress.class: alb
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: meu-app.com.br
      paths:
        - path: /frontend
          pathType: Prefix
          backend:
            service:
              name: frontend
              port:
                number: 80
  tls: []

resources:
   limits:
     cpu: 150m
     memory: 512Mi
   requests:
     cpu: 100m
     memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

